
modLoader="javafml" #mandatory

loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="ARR"
[[mods]] #mandatory

modId="amendments" #mandatory
version = "${version}"
displayName="Amendments" #mandatory
logoFile="icon.png" #optional
authors="MehVahdJukaar, Plantkillable" #optional

description='''Jukebox Visual Overhaul'''

displayURL="https://www.curseforge.com/minecraft/mc-mods/amendments" #optional
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/amendments/issues" #optional
itemIcon="minecraft:painting" #catalogue icon


[[dependencies.amendments]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.amendments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.amendments]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.5.16,)"
    ordering="NONE"
    side="BOTH"
